# Generated by Django 5.2.1 on 2025-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('residente', 'Residente'), ('visitante', 'Visitante')], max_length=50)),
                ('vehiculo', models.BooleanField(default=False)),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
