# Generated by Django 5.2.1 on 2025-06-12 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen_acceso', models.ImageField(blank=True, null=True, upload_to='logs/')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.persona')),
            ],
        ),
    ]
